apiVersion: v1
kind: PersistentVolume
metadata:
    name: backend-cache-pv
    namespace: kube-cicd
    labels:
      pvname: backend-cache-pv
spec:
    capacity:
      storage: 500Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    mountOptions:
      - vers=3
      - nolock,tcp,noresvport
    nfs:
      path: /data-ci/backend-cache       # nfs服务端挂载目录
      server: 10.10.10.11
 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backend-cache-pvc
  namespace: kube-cicd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      pvname: backend-cache-pv
