apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-gitlab-backend-runner
  name: k8s-gitlab-backend-runner
  namespace: kube-cicd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: k8s-gitlab-backend-runner
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "9252"
        prometheus.io/scrape: "true"
      labels:
        app: k8s-gitlab-backend-runner
    spec:
      containers:
      - command:
        - /bin/bash
        - /scripts/entrypoint
        env:
        - name: CI_SERVER_URL
          value: https://git.example.com/         # gitlab地址
        - name: CLONE_URL
        - name: RUNNER_EXECUTOR
          value: kubernetes
        - name: REGISTER_LOCKED
          value: "true"
        - name: RUNNER_TAG_LIST
          value: k8s-runner-backend          # gitlab runner tag
        - name: KUBERNETES_IMAGE
          value: ubuntu:16.04
        - name: KUBERNETES_PRIVILEGED
          value: "true"
        - name: KUBERNETES_NAMESPACE
          value: kube-cicd
        - name: KUBERNETES_NODE_SELECTOR
          value: "function:cicd"              # 运行gitlab runner的k8s节点label
        - name: KUBERNETES_CPU_LIMIT
          value: "1"
        - name: KUBERNETES_MEMORY_LIMIT
          value: "3Gi"
        - name: KUBERNETES_CPU_REQUEST
          value: "400m"
        - name: KUBERNETES_MEMORY_REQUEST
          value: "1Gi"
        - name: KUBERNETES_SERVICE_ACCOUNT
        - name: KUBERNETES_SERVICE_CPU_LIMIT
        - name: KUBERNETES_SERVICE_MEMORY_LIMIT
        - name: KUBERNETES_SERVICE_CPU_REQUEST
        - name: KUBERNETES_SERVICE_MEMORY_REQUEST
        - name: KUBERNETES_HELPER_CPU_LIMIT
        - name: KUBERNETES_HELPER_MEMORY_LIMIT
        - name: KUBERNETES_HELPER_CPU_REQUEST
        - name: KUBERNETES_HELPER_MEMORY_REQUEST
        - name: KUBERNETES_HELPER_IMAGE
        - name: KUBERNETES_PULL_POLICY
          value: if-not-present
        - name: CUSTOM_BUILD_DIR_ENABLED
          value: "true"
        - name: RUNNER_PRE_CLONE_SCRIPT
          value: echo '10.10.10.10 git.example.com' >> /etc/hosts           # 如果gitlab地址不是公网域名解析, 建议加上该配置
        image: gitlab-runner:alpine-v12.1.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - gitlab-runner
              - unregister
              - --all-runners
        livenessProbe:
          exec:
            command:
            - /usr/bin/pgrep
            - gitlab.*runner
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: k8s-gitlab-backend-runner
        ports:
        - containerPort: 9252
          name: metrics
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/bin/pgrep
            - gitlab.*runner
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets
          name: runner-secrets
        - mountPath: /home/gitlab-runner/.gitlab-runner
          name: etc-gitlab-runner
        - mountPath: /scripts
          name: scripts
        - name: gitlab-tls-configmap
          mountPath: /home/gitlab-runner/
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - /config/configure
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        name: configure
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets
          name: runner-secrets
        - mountPath: /config
          name: scripts
          readOnly: true
        - mountPath: /init-secrets
          name: init-runner-secrets
          readOnly: true
        - name: gitlab-tls-configmap
          mountPath: /home/gitlab-runner/
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65533
        runAsUser: 100
      serviceAccount: k8s-ack-gitlab-runner
      serviceAccountName: k8s-ack-gitlab-runner
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gitlab-tls-configmap
        configMap:
          name: gitlab-tls-configmap
      - emptyDir:
          medium: Memory
        name: runner-secrets
      - emptyDir:
          medium: Memory
        name: etc-gitlab-runner
      - name: init-runner-secrets
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: runner-registration-token
                path: runner-registration-token
              - key: runner-token
                path: runner-token
              name: k8s-ack-gitlab-runner
      - configMap:
          defaultMode: 420
          name: k8s-gitlab-runner
        name: scripts
status: {}
