apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-tls-configmap
  namespace: kube-cicd
data:
  git.example.com.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDwjCCAqqgAwIBAgICEjAwDQYJKoZIhvcNAQELBQAwfDELMAkGA1UEBhMCQ04x
    EDAOBgNVBAgMB0JlaWppbmcxEDAOBgNVBAcMB0JlaWppbmcxFjAUBgNVBAoMDUNl
    Y0Nsb3VkIEluYy4xEjAQBgNVBAsMCURldiBEZXB0LjEdMBsGA1UEAwwUQ3VzdG9t
    IENDbG91ZCBEZXYgQ0EwHhcNMjEwNTMxMDIxNzUxWhcNMjMwNjIwMDIxNzUxWjBi
    MQswCQYDVQQGEwJDTjEQMA4GA1UECAwHQmVpamluZzEWMBQGA1UECgwNQ2VjQ2xv
    dWQgSW5jLjESMBAGA1UECwwJRGV2IERlcHQuMRUwEwYDVQQDDAwxMC4yNTUuMC4x
    MDAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDXU4JKPU2498M4KGhP
    Q17ibLyfbQfGQwb1KMsoxExXiDHdH2btJnxZ93t01jumtx91nv3EQfuE/cMqOCB1
    5vQEW3J7AdsNc79jKJGXQ3WGksZqYQJ0kGYfYo6XPtcI71MvxTKrhTq7hI6e8j1f
    yWiTzcBbWQB6KOCPd7F4eOrPsXK7pSGTw7q1xaxVYbZ0DZt+gAobdyjVEMXW2M2G
    VRkMOJgeo6Qka9wBxHjldk2r8wRiPT5g30h15vUpglqy2jjqRTdVdfrC+jbf4UI6
    kK2Jf00iJD5OIWjmHjKXvvs+MrsbdkOCTJ8iWOl0qgsdsKuieGmUovBSfZZe+CPf
    24fTAgMBAAGjaDBmMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgKkMB0G
    A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAkBgNVHREEHTAbhwQK/wBkhwQK
    ICsCgg1jb2RlLmNlc3RjLmNuMA0GCSqGSIb3DQEBCwUAA4IBAQBBYBZGf6Q2QaDG
    QWWDYCnBMaS3r4d0CWhBBNoEPWaGJMWzM7UlH+73/MTGkQj/2aA9NfaXkwFJOYxY
    O/fWAYYx2KgTK88bYYd41kmVPA0TOwzuzPWWxJItMh/rbnsLISHbVpPdXl7y85XJ
    4T+6SJ0a7a7+yvTG9nuzyiaKWFIY/8YJyTNl72lsOowKBfxK0E6F2HZumQ7dRXQm
    r1b3tTZ5mliMrXLxtRemWUN9OVlyyShnMCUhIrEXFvpXPfeg4H9zzualCWqFGkYg
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    xxxx
    -----END CERTIFICATE-----
