apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: k8s-ack-gitlab-runner
  name: k8s-ack-gitlab-runner
  namespace: kube-cicd
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: k8s-ack-gitlab-runner
  name: k8s-ack-gitlab-runner
  namespace: kube-cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-ack-gitlab-runner
subjects:
- kind: ServiceAccount
  name: k8s-ack-gitlab-runner
  namespace: kube-cicd

